/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class FormLaporan extends javax.swing.JFrame {

    private Connection conn;
    
    public FormLaporan() {
        initComponents();
        
        conn = Helper.Database.OpenConnection();
        load_table();
    }
    
    private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Menu");
        model.addColumn("Nama");
        model.addColumn("Jenis");
        model.addColumn("Harga");

        //Menampilkan data kedalam tabel
        try {
            String query = "SELECT * FROM Menu";
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4)});
                }
            tblLaporan.setModel(model);
        }catch (Exception e) {
                        
        }
                
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnToMenu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnToMenu1 = new javax.swing.JButton();
        btnToMenu2 = new javax.swing.JButton();
        btnToMenu3 = new javax.swing.JButton();
        btnToMenu4 = new javax.swing.JButton();
        btnToMenu5 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        riwayatTransaksi = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jLabel49 = new javax.swing.JLabel();
        txtJenisMenu2 = new javax.swing.JComboBox<>();
        txtJenisMenu3 = new javax.swing.JComboBox<>();
        laporanStok = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMenu2 = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        txtJenisMenu4 = new javax.swing.JComboBox<>();
        txtJenisMenu5 = new javax.swing.JComboBox<>();
        laporanKeluar = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMenu3 = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        txtJenisMenu6 = new javax.swing.JComboBox<>();
        txtJenisMenu7 = new javax.swing.JComboBox<>();
        laporanLaba = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        txtJenisMenu = new javax.swing.JComboBox<>();
        txtJenisMenu1 = new javax.swing.JComboBox<>();
        laporanStokMasuk = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMenu4 = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        txtJenisMenu8 = new javax.swing.JComboBox<>();
        txtJenisMenu9 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodyPanel.setBackground(new java.awt.Color(140, 2, 2));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnToMenu.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu.setText("Dashboard");
        btnToMenu.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenuActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setText("Keluar");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnToMenu1.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu1.setText("Riwayat Transaksi");
        btnToMenu1.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu1ActionPerformed(evt);
            }
        });

        btnToMenu2.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu2.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu2.setText("Laporan Stok");
        btnToMenu2.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu2ActionPerformed(evt);
            }
        });

        btnToMenu3.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu3.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu3.setText("Laporan Keluar");
        btnToMenu3.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu3ActionPerformed(evt);
            }
        });

        btnToMenu4.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu4.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu4.setText("Laporan Laba");
        btnToMenu4.setPreferredSize(new java.awt.Dimension(136, 100));
        btnToMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu4ActionPerformed(evt);
            }
        });

        btnToMenu5.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu5.setText("Laporan S. Masuk");
        btnToMenu5.setPreferredSize(new java.awt.Dimension(131, 21));
        btnToMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(140, 2, 2));
        mainPanel.setLayout(new java.awt.CardLayout());

        riwayatTransaksi.setBackground(new java.awt.Color(144, 2, 2));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Bulan");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Tahun");

        tblLaporan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Jenis", "ID Transaksi", "Harga"
            }
        ));
        tblLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaporanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLaporan);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Riwayat Transaksi");

        txtJenisMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu2.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu2ActionPerformed(evt);
            }
        });

        txtJenisMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu3.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatTransaksiLayout = new javax.swing.GroupLayout(riwayatTransaksi);
        riwayatTransaksi.setLayout(riwayatTransaksiLayout);
        riwayatTransaksiLayout.setHorizontalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        riwayatTransaksiLayout.setVerticalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(riwayatTransaksi, "card2");

        laporanStok.setBackground(new java.awt.Color(144, 2, 2));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Bulan");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Tahun");

        tblMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Bahan", "ID Bahan", "Tanggal", "Stok"
            }
        ));
        tblMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenu2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMenu2);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Laporan Stok");

        txtJenisMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu4.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu4ActionPerformed(evt);
            }
        });

        txtJenisMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu5.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanStokLayout = new javax.swing.GroupLayout(laporanStok);
        laporanStok.setLayout(laporanStokLayout);
        laporanStokLayout.setHorizontalGroup(
            laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokLayout.createSequentialGroup()
                .addGroup(laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanStokLayout.setVerticalGroup(
            laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(laporanStok, "card2");

        laporanKeluar.setBackground(new java.awt.Color(144, 2, 2));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Bulan");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Tahun");

        tblMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Deskripsi", "Total"
            }
        ));
        tblMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenu3MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblMenu3);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Laporan Pengeluaran");

        txtJenisMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu6.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu6ActionPerformed(evt);
            }
        });

        txtJenisMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu7.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanKeluarLayout = new javax.swing.GroupLayout(laporanKeluar);
        laporanKeluar.setLayout(laporanKeluarLayout);
        laporanKeluarLayout.setHorizontalGroup(
            laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanKeluarLayout.createSequentialGroup()
                .addGroup(laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanKeluarLayout.setVerticalGroup(
            laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanKeluarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(laporanKeluar, "card2");

        laporanLaba.setBackground(new java.awt.Color(144, 2, 2));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Bulan");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Tahun");

        tblMenu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Pengeluaran", "Pendapatan", "Laba bersih", "Tanggal"
            }
        ));
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMenu);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Laporan Laba");

        txtJenisMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenuActionPerformed(evt);
            }
        });

        txtJenisMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu1.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanLabaLayout = new javax.swing.GroupLayout(laporanLaba);
        laporanLaba.setLayout(laporanLabaLayout);
        laporanLabaLayout.setHorizontalGroup(
            laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanLabaLayout.createSequentialGroup()
                .addGroup(laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanLabaLayout.setVerticalGroup(
            laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanLabaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(laporanLaba, "card2");

        laporanStokMasuk.setBackground(new java.awt.Color(144, 2, 2));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Bulan");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Tahun");

        tblMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Bahan", "Harga Pasar", "Harga Beli"
            }
        ));
        tblMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenu4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblMenu4);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Laporan Stok Masuk");

        txtJenisMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu8.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu8ActionPerformed(evt);
            }
        });

        txtJenisMenu9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu9.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanStokMasukLayout = new javax.swing.GroupLayout(laporanStokMasuk);
        laporanStokMasuk.setLayout(laporanStokMasukLayout);
        laporanStokMasukLayout.setHorizontalGroup(
            laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokMasukLayout.createSequentialGroup()
                .addGroup(laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanStokMasukLayout.setVerticalGroup(
            laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokMasukLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        mainPanel.add(laporanStokMasuk, "card2");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenuActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(laporanLaba);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnToMenuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose(); // this will close current login box window

        //this will open a nextpage window.
        FormLogin page = new FormLogin();
        page.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        int baris = tblMenu.rowAtPoint(evt.getPoint());
        String idMenu = tblMenu.getValueAt(baris, 1).toString();
//        txtIDMenu.setText(idMenu);
//        
//        txtNamaMenu.setText((String) tblMenu.getValueAt(baris, 2));
//        txtHargaMenu.setText((String) tblMenu.getValueAt(baris, 3));
        txtJenisMenu.setSelectedItem((String) tblMenu.getValueAt(baris, 4));
    }//GEN-LAST:event_tblMenuMouseClicked

    private void txtJenisMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenuActionPerformed

    private void txtJenisMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu1ActionPerformed

    private void btnToMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu1ActionPerformed

    private void btnToMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu2ActionPerformed

    private void btnToMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu3ActionPerformed

    private void btnToMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu4ActionPerformed

    private void btnToMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu5ActionPerformed

    private void tblLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLaporanMouseClicked

    private void txtJenisMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu2ActionPerformed

    private void txtJenisMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu3ActionPerformed

    private void tblMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenu2MouseClicked

    private void txtJenisMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu4ActionPerformed

    private void txtJenisMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu5ActionPerformed

    private void tblMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenu3MouseClicked

    private void txtJenisMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu6ActionPerformed

    private void txtJenisMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu7ActionPerformed

    private void tblMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenu4MouseClicked

    private void txtJenisMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu8ActionPerformed

    private void txtJenisMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnToMenu;
    private javax.swing.JButton btnToMenu1;
    private javax.swing.JButton btnToMenu2;
    private javax.swing.JButton btnToMenu3;
    private javax.swing.JButton btnToMenu4;
    private javax.swing.JButton btnToMenu5;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel laporanKeluar;
    private javax.swing.JPanel laporanLaba;
    private javax.swing.JPanel laporanStok;
    private javax.swing.JPanel laporanStokMasuk;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel riwayatTransaksi;
    private javax.swing.JTable tblLaporan;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblMenu2;
    private javax.swing.JTable tblMenu3;
    private javax.swing.JTable tblMenu4;
    private javax.swing.JComboBox<String> txtJenisMenu;
    private javax.swing.JComboBox<String> txtJenisMenu1;
    private javax.swing.JComboBox<String> txtJenisMenu2;
    private javax.swing.JComboBox<String> txtJenisMenu3;
    private javax.swing.JComboBox<String> txtJenisMenu4;
    private javax.swing.JComboBox<String> txtJenisMenu5;
    private javax.swing.JComboBox<String> txtJenisMenu6;
    private javax.swing.JComboBox<String> txtJenisMenu7;
    private javax.swing.JComboBox<String> txtJenisMenu8;
    private javax.swing.JComboBox<String> txtJenisMenu9;
    // End of variables declaration//GEN-END:variables
}
