/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Component.BuatLaporan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

public class FormLaporan extends javax.swing.JFrame {

    private Connection conn;
    
    private HashMap<String, Object[]> dataStokBahan = new HashMap<>();
    
    public FormLaporan() {
        initComponents();
        
        conn = Helper.Database.OpenConnection();
        loadTableLaporanLaba();
        loadTableLaporanKeluar();
        loadTableRiwayatTransaksi();
        
    }
    private void loadTableLaporanLaba() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan Laba");
        model.addColumn("Tanggal laporan");
        model.addColumn("Total Pendapatan");
        model.addColumn("Total pengeluaran");
        model.addColumn("Laba Bersih");

        //Menampilkan data kedalam tabel
        try {
            String query = "SELECT * FROM laporan_laba";
            PreparedStatement ps = conn.prepareStatement(query);       
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
                }
            tblLaporanLaba.setModel(model);
        }catch (Exception e) {
        e.printStackTrace();                
        }                           
    }
    
    private void loadTableRiwayatTransaksi() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Jenis pemesanan");
        model.addColumn("Total Harga");
        model.addColumn("Total Pembayaran");
        model.addColumn("Kembalian");
        model.addColumn("Tanggal Transaksi");
        

        //Menampilkan data kedalam tabel
        try {
            String query = "SELECT `id_transaksi`, `jenis_pesanan`, `total_harga`, `total_pembayaran`, `kembalian`,`tanggal_transaksi` FROM `transaksi`";
            PreparedStatement ps = conn.prepareStatement(query);       
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
                }
            tblRiwayatTransaksi.setModel(model);
        }catch (Exception e) {
        e.printStackTrace();                
        }                           
    }
    
    private void loadTableLaporanKeluar() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan Pengeluaran");
        model.addColumn("Tanggal Laporan");
        model.addColumn("Deskripsi Pengeluaran");
        model.addColumn("Total pengeluaran");
        

        //Menampilkan data kedalam tabel
        try {
            String query = "SELECT * FROM laporan_pengeluaran";
            PreparedStatement ps = conn.prepareStatement(query);       
            Statement stm=conn.createStatement();
            ResultSet res=stm.executeQuery(query);
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4)});
                }
            tblLaporanPengeluaran.setModel(model);
        }catch (Exception e) {
        e.printStackTrace();                
        }                           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnToMenu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnToRiwayatTransaksi = new javax.swing.JButton();
        btnToKartuStok = new javax.swing.JButton();
        btnToLaporanPengeluaran = new javax.swing.JButton();
        btnToLaporanLaba = new javax.swing.JButton();
        btnToMenu5 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        riwayatTransaksi = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRiwayatTransaksi = new javax.swing.JTable();
        jLabel49 = new javax.swing.JLabel();
        txtJenisMenu2 = new javax.swing.JComboBox<>();
        txtJenisMenu3 = new javax.swing.JComboBox<>();
        btnBuatLaporan = new javax.swing.JButton();
        laporanStok = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMenu2 = new javax.swing.JTable();
        jLabel51 = new javax.swing.JLabel();
        txtJenisMenu4 = new javax.swing.JComboBox<>();
        txtJenisMenu5 = new javax.swing.JComboBox<>();
        laporanKeluar = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLaporanPengeluaran = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        txtJenisMenu6 = new javax.swing.JComboBox<>();
        txtJenisMenu7 = new javax.swing.JComboBox<>();
        laporanLaba = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLaporanLaba = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        txtJenisMenu = new javax.swing.JComboBox<>();
        txtJenisMenu1 = new javax.swing.JComboBox<>();
        laporanStokMasuk = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMenu4 = new javax.swing.JTable();
        jLabel57 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        cbTahun = new javax.swing.JComboBox<>();
        kartuStok = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtJenisMenu8 = new javax.swing.JComboBox<>();
        txtJenisMenu9 = new javax.swing.JComboBox<>();
        btnEkspor = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        txtPilihBahan = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblKartuStok = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bodyPanel.setBackground(new java.awt.Color(140, 2, 2));

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnToMenu.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu.setText("Dashboard");
        btnToMenu.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenuActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setText("Keluar");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnToRiwayatTransaksi.setBackground(new java.awt.Color(198, 40, 40));
        btnToRiwayatTransaksi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToRiwayatTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnToRiwayatTransaksi.setText("Riwayat Transaksi");
        btnToRiwayatTransaksi.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToRiwayatTransaksiActionPerformed(evt);
            }
        });

        btnToKartuStok.setBackground(new java.awt.Color(198, 40, 40));
        btnToKartuStok.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToKartuStok.setForeground(new java.awt.Color(255, 255, 255));
        btnToKartuStok.setText("Kartu Stok");
        btnToKartuStok.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToKartuStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToKartuStokActionPerformed(evt);
            }
        });

        btnToLaporanPengeluaran.setBackground(new java.awt.Color(198, 40, 40));
        btnToLaporanPengeluaran.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToLaporanPengeluaran.setForeground(new java.awt.Color(255, 255, 255));
        btnToLaporanPengeluaran.setText("Laporan Keluar");
        btnToLaporanPengeluaran.setPreferredSize(new java.awt.Dimension(95, 21));
        btnToLaporanPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLaporanPengeluaranActionPerformed(evt);
            }
        });

        btnToLaporanLaba.setBackground(new java.awt.Color(198, 40, 40));
        btnToLaporanLaba.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToLaporanLaba.setForeground(new java.awt.Color(255, 255, 255));
        btnToLaporanLaba.setText("Laporan Laba");
        btnToLaporanLaba.setPreferredSize(new java.awt.Dimension(136, 100));
        btnToLaporanLaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToLaporanLabaActionPerformed(evt);
            }
        });

        btnToMenu5.setBackground(new java.awt.Color(198, 40, 40));
        btnToMenu5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnToMenu5.setForeground(new java.awt.Color(255, 255, 255));
        btnToMenu5.setText("Laporan S. Masuk");
        btnToMenu5.setPreferredSize(new java.awt.Dimension(131, 21));
        btnToMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToMenu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToKartuStok, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToLaporanPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToLaporanLaba, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToKartuStok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToLaporanPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToLaporanLaba, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(140, 2, 2));
        mainPanel.setLayout(new java.awt.CardLayout());

        riwayatTransaksi.setBackground(new java.awt.Color(144, 2, 2));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Bulan");

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Tahun");

        tblRiwayatTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblRiwayatTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Jenis", "Harga", "Bayar", "Kembalian"
            }
        ));
        tblRiwayatTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRiwayatTransaksiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblRiwayatTransaksi);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Riwayat Transaksi");

        txtJenisMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu2.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu2ActionPerformed(evt);
            }
        });

        txtJenisMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu3.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu3ActionPerformed(evt);
            }
        });

        btnBuatLaporan.setBackground(new java.awt.Color(204, 204, 204));
        btnBuatLaporan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBuatLaporan.setForeground(new java.awt.Color(51, 51, 51));
        btnBuatLaporan.setText("Buat Laporan");
        btnBuatLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout riwayatTransaksiLayout = new javax.swing.GroupLayout(riwayatTransaksi);
        riwayatTransaksi.setLayout(riwayatTransaksiLayout);
        riwayatTransaksiLayout.setHorizontalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, riwayatTransaksiLayout.createSequentialGroup()
                            .addGap(309, 309, 309)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtJenisMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtJenisMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuatLaporan))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, riwayatTransaksiLayout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        riwayatTransaksiLayout.setVerticalGroup(
            riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(riwayatTransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(riwayatTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuatLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        mainPanel.add(riwayatTransaksi, "card2");

        laporanStok.setBackground(new java.awt.Color(144, 2, 2));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Bulan");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Tahun");

        tblMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Bahan", "ID Bahan", "Tanggal", "Stok"
            }
        ));
        tblMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenu2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblMenu2);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Laporan Stok");

        txtJenisMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu4.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu4ActionPerformed(evt);
            }
        });

        txtJenisMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu5.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanStokLayout = new javax.swing.GroupLayout(laporanStok);
        laporanStok.setLayout(laporanStokLayout);
        laporanStokLayout.setHorizontalGroup(
            laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokLayout.createSequentialGroup()
                .addGroup(laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanStokLayout.setVerticalGroup(
            laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainPanel.add(laporanStok, "card2");

        laporanKeluar.setBackground(new java.awt.Color(144, 2, 2));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Bulan");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Tahun");

        tblLaporanPengeluaran.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLaporanPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Deskripsi", "Total"
            }
        ));
        tblLaporanPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaporanPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblLaporanPengeluaran);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Laporan Pengeluaran");

        txtJenisMenu6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu6.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu6ActionPerformed(evt);
            }
        });

        txtJenisMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu7.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanKeluarLayout = new javax.swing.GroupLayout(laporanKeluar);
        laporanKeluar.setLayout(laporanKeluarLayout);
        laporanKeluarLayout.setHorizontalGroup(
            laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanKeluarLayout.createSequentialGroup()
                .addGroup(laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanKeluarLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanKeluarLayout.setVerticalGroup(
            laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanKeluarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainPanel.add(laporanKeluar, "card2");

        laporanLaba.setBackground(new java.awt.Color(144, 2, 2));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Bulan");

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Tahun");

        tblLaporanLaba.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblLaporanLaba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Pendapatan", "Pengeluaran", "Laba bersih"
            }
        ));
        tblLaporanLaba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaporanLabaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLaporanLaba);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Laporan Laba");

        txtJenisMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenuActionPerformed(evt);
            }
        });

        txtJenisMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu1.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanLabaLayout = new javax.swing.GroupLayout(laporanLaba);
        laporanLaba.setLayout(laporanLabaLayout);
        laporanLabaLayout.setHorizontalGroup(
            laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanLabaLayout.createSequentialGroup()
                .addGroup(laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanLabaLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanLabaLayout.setVerticalGroup(
            laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanLabaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanLabaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJenisMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainPanel.add(laporanLaba, "card2");

        laporanStokMasuk.setBackground(new java.awt.Color(144, 2, 2));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Bulan");

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Tahun");

        tblMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblMenu4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Bahan", "Harga Pasar", "Harga Beli"
            }
        ));
        tblMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenu4MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblMenu4);

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Laporan Stok Masuk");

        cbBulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbBulan.setPreferredSize(new java.awt.Dimension(64, 22));
        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });

        cbTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        cbTahun.setPreferredSize(new java.awt.Dimension(64, 22));
        cbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout laporanStokMasukLayout = new javax.swing.GroupLayout(laporanStokMasuk);
        laporanStokMasuk.setLayout(laporanStokMasukLayout);
        laporanStokMasukLayout.setHorizontalGroup(
            laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokMasukLayout.createSequentialGroup()
                .addGroup(laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(laporanStokMasukLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        laporanStokMasukLayout.setVerticalGroup(
            laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanStokMasukLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(laporanStokMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        mainPanel.add(laporanStokMasuk, "card2");

        kartuStok.setBackground(new java.awt.Color(144, 2, 2));

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Bulan");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Tahun");

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Kartu Stok");

        txtJenisMenu8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        txtJenisMenu8.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu8ActionPerformed(evt);
            }
        });

        txtJenisMenu9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtJenisMenu9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));
        txtJenisMenu9.setPreferredSize(new java.awt.Dimension(64, 22));
        txtJenisMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMenu9ActionPerformed(evt);
            }
        });

        btnEkspor.setBackground(new java.awt.Color(204, 204, 204));
        btnEkspor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEkspor.setForeground(new java.awt.Color(51, 51, 51));
        btnEkspor.setText("Cetak");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Bahan");

        txtPilihBahan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPilihBahan.setPreferredSize(new java.awt.Dimension(64, 22));
        txtPilihBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilihBahanActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        tblKartuStok.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblKartuStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Jenis", "Harga", "Bayar", "Kembalian"
            }
        ));
        tblKartuStok.setRowHeight(40);
        tblKartuStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKartuStokMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblKartuStok);

        jPanel1.add(jScrollPane8, "card2");

        javax.swing.GroupLayout kartuStokLayout = new javax.swing.GroupLayout(kartuStok);
        kartuStok.setLayout(kartuStokLayout);
        kartuStokLayout.setHorizontalGroup(
            kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStokLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kartuStokLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kartuStokLayout.createSequentialGroup()
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPilihBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJenisMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEkspor)))
                .addGap(19, 19, 19))
        );
        kartuStokLayout.setVerticalGroup(
            kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kartuStokLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPilihBahan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kartuStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJenisMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJenisMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEkspor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        mainPanel.add(kartuStok, "card2");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenuActionPerformed
        
    }//GEN-LAST:event_btnToMenuActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose(); // this will close current login box window

        //this will open a nextpage window.
        FormLogin page = new FormLogin();
        page.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tblLaporanLabaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaporanLabaMouseClicked
        int baris = tblLaporanLaba.rowAtPoint(evt.getPoint());
        String id = tblLaporanLaba.getValueAt(baris, 0).toString();
        String tanggal = tblLaporanLaba.getValueAt(baris, 1).toString();
        String pendapatan = tblLaporanLaba.getValueAt(baris, 2).toString();
        String pengeluran = tblLaporanLaba.getValueAt(baris, 3).toString();
        String labaBersih = tblLaporanLaba.getValueAt(baris, 4).toString();
    }//GEN-LAST:event_tblLaporanLabaMouseClicked

    private void txtJenisMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenuActionPerformed

    private void txtJenisMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu1ActionPerformed

    private void btnToRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToRiwayatTransaksiActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(riwayatTransaksi);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        loadTableRiwayatTransaksi();
    }//GEN-LAST:event_btnToRiwayatTransaksiActionPerformed

    private void btnToKartuStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToKartuStokActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(kartuStok);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        txtPilihBahan.revalidate();
        txtPilihBahan.repaint();
        
        loadDataStokBahan();
        loadKartuStok();
    }//GEN-LAST:event_btnToKartuStokActionPerformed

    private void btnToLaporanPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLaporanPengeluaranActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(laporanKeluar);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        loadTableLaporanKeluar();
    }//GEN-LAST:event_btnToLaporanPengeluaranActionPerformed

    private void btnToLaporanLabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToLaporanLabaActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(laporanLaba);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        loadTableLaporanLaba();
    }//GEN-LAST:event_btnToLaporanLabaActionPerformed

    private void btnToMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToMenu5ActionPerformed

    private void tblRiwayatTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRiwayatTransaksiMouseClicked
        int baris = tblRiwayatTransaksi.rowAtPoint(evt.getPoint());
        String id = tblRiwayatTransaksi.getValueAt(baris, 0).toString();
        String jenis = tblRiwayatTransaksi.getValueAt(baris, 1).toString();
        String harga = tblRiwayatTransaksi.getValueAt(baris, 2).toString();
        String bayar = tblRiwayatTransaksi.getValueAt(baris, 3).toString();
        String kembalian = tblRiwayatTransaksi.getValueAt(baris, 4).toString();
        String tanggal = tblRiwayatTransaksi.getValueAt(baris, 5).toString();
    }//GEN-LAST:event_tblRiwayatTransaksiMouseClicked

    private void txtJenisMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu2ActionPerformed

    private void txtJenisMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu3ActionPerformed

    private void tblMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenu2MouseClicked

    private void txtJenisMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu4ActionPerformed

    private void txtJenisMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu5ActionPerformed

    private void tblLaporanPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaporanPengeluaranMouseClicked
        int baris = tblLaporanLaba.rowAtPoint(evt.getPoint());
        String idlaporanPengeluaran = tblLaporanPengeluaran.getValueAt(baris, 0).toString();
        String tanggalLaporan = tblLaporanPengeluaran.getValueAt(baris, 1).toString();
        String deskripsiPengeluaran = tblLaporanPengeluaran.getValueAt(baris, 2).toString();
        String totalpengeluran = tblLaporanPengeluaran.getValueAt(baris, 3).toString();
    }//GEN-LAST:event_tblLaporanPengeluaranMouseClicked

    private void txtJenisMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu6ActionPerformed

    private void txtJenisMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu7ActionPerformed

    private void tblMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMenu4MouseClicked

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBulanActionPerformed

    private void cbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTahunActionPerformed

    private void btnBuatLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatLaporanActionPerformed
        BuatLaporan BuatLaporan = new BuatLaporan();
        BuatLaporan.setVisible(true);
    }//GEN-LAST:event_btnBuatLaporanActionPerformed

    private void tblKartuStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKartuStokMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKartuStokMouseClicked

    private void txtJenisMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu8ActionPerformed

    private void txtJenisMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMenu9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMenu9ActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEksporActionPerformed

    private void txtPilihBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilihBahanActionPerformed
        loadKartuStok();
    }//GEN-LAST:event_txtPilihBahanActionPerformed

    private void loadDataStokBahan() {
        dataStokBahan.clear();
        txtPilihBahan.removeAllItems();
               
        try {
            String query = "SELECT * FROM bahan";
            Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(query);

            while (res.next()) {
                int idBahan = res.getInt("id_bahan");
                String namaBahan = res.getString("nama_bahan");
                int stokSistem = res.getInt("stok_bahan");
                String satuanSistem = res.getString("satuan");

                // Menyimpan data ke HashMap
                dataStokBahan.put(namaBahan, new Object[]{idBahan, stokSistem, satuanSistem});

                // Menambahkan nama bahan ke combobox
                txtPilihBahan.addItem(namaBahan);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void loadKartuStok() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tanggal");
        model.addColumn("Keterangan");
        model.addColumn("Jumlah Masuk");
        model.addColumn("Jumlah Keluar");
        model.addColumn("Saldo");
        
        String namaBahan = (String) txtPilihBahan.getSelectedItem();
        Object[] data = dataStokBahan.get(namaBahan);
        int idBahan = (int) data[0]; // ID bahan
        
        try {
            //Menampilkan data kedalam tabel
            String query = "SELECT tanggal, keterangan, jumlah_masuk, jumlah_keluar, saldo FROM kartu_stok WHERE id_bahan = ? ORDER BY tanggal, waktu ASC";
            
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, idBahan);
            
            ResultSet res = ps.executeQuery();
            
            boolean hasData = false;
            while(res.next()){
                hasData = true;
                
                Object[] row = {
                    res.getDate("tanggal"),
                    res.getString("keterangan"),
                    res.getInt("jumlah_masuk"),
                    res.getInt("jumlah_keluar"),
                    res.getInt("saldo")
                };
                model.addRow(row);
                tblKartuStok.setModel(model);
            }
            
            if (!hasData) {
                Object[] emptyRow = {"-", "No data available", 0, 0, 0};
                model.addRow(emptyRow);
                tblKartuStok.setVisible(false);
            } else {
                tblKartuStok.setVisible(true);
            }
            
            /**
             * @param args the command line arguments
             */
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnBuatLaporan;
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnToKartuStok;
    private javax.swing.JButton btnToLaporanLaba;
    private javax.swing.JButton btnToLaporanPengeluaran;
    private javax.swing.JButton btnToMenu;
    private javax.swing.JButton btnToMenu5;
    private javax.swing.JButton btnToRiwayatTransaksi;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JComboBox<String> cbTahun;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel kartuStok;
    private javax.swing.JPanel laporanKeluar;
    private javax.swing.JPanel laporanLaba;
    private javax.swing.JPanel laporanStok;
    private javax.swing.JPanel laporanStokMasuk;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel riwayatTransaksi;
    private javax.swing.JTable tblKartuStok;
    private javax.swing.JTable tblLaporanLaba;
    private javax.swing.JTable tblLaporanPengeluaran;
    private javax.swing.JTable tblMenu2;
    private javax.swing.JTable tblMenu4;
    private javax.swing.JTable tblRiwayatTransaksi;
    private javax.swing.JComboBox<String> txtJenisMenu;
    private javax.swing.JComboBox<String> txtJenisMenu1;
    private javax.swing.JComboBox<String> txtJenisMenu2;
    private javax.swing.JComboBox<String> txtJenisMenu3;
    private javax.swing.JComboBox<String> txtJenisMenu4;
    private javax.swing.JComboBox<String> txtJenisMenu5;
    private javax.swing.JComboBox<String> txtJenisMenu6;
    private javax.swing.JComboBox<String> txtJenisMenu7;
    private javax.swing.JComboBox<String> txtJenisMenu8;
    private javax.swing.JComboBox<String> txtJenisMenu9;
    private javax.swing.JComboBox<String> txtPilihBahan;
    // End of variables declaration//GEN-END:variables
}
